/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiCreateAgentAPIKeyOutputFromDiscriminatorValue, createApiListAgentAPIKeysOutputFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeApiCreateAgentAPIKeyInputPublic, serializeApiCreateAgentAPIKeyOutput, type ApiCreateAgentAPIKeyInputPublic, type ApiCreateAgentAPIKeyOutput, type ApiListAgentAPIKeysOutput, type ErrorEscaped } from '../../../../../models/index.js';
// @ts-ignore
import { type WithApi_key_uuItemRequestBuilder, WithApi_key_uuItemRequestBuilderNavigationMetadata, WithApi_key_uuItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/gen-ai/agents/{agent_uu-id}/api_keys
 */
export interface Api_keysRequestBuilder extends BaseRequestBuilder<Api_keysRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v2.genAi.agents.item.api_keys.item collection
     * @param api_key_uuid API key for an agent.
     * @returns {WithApi_key_uuItemRequestBuilder}
     */
     byApi_key_uuid(api_key_uuid: string) : WithApi_key_uuItemRequestBuilder;
    /**
     * To list all agent API keys, send a GET request to `/v2/gen-ai/agents/{agent_uuid}/api_keys`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiListAgentAPIKeysOutput>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<Api_keysRequestBuilderGetQueryParameters> | undefined) : Promise<ApiListAgentAPIKeysOutput | undefined>;
    /**
     * To create an agent API key, send a POST request to `/v2/gen-ai/agents/{agent_uuid}/api_keys`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiCreateAgentAPIKeyOutput>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     post(body: ApiCreateAgentAPIKeyInputPublic, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApiCreateAgentAPIKeyOutput | undefined>;
    /**
     * To list all agent API keys, send a GET request to `/v2/gen-ai/agents/{agent_uuid}/api_keys`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Api_keysRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * To create an agent API key, send a POST request to `/v2/gen-ai/agents/{agent_uuid}/api_keys`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ApiCreateAgentAPIKeyInputPublic, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * To list all agent API keys, send a GET request to `/v2/gen-ai/agents/{agent_uuid}/api_keys`.
 */
export interface Api_keysRequestBuilderGetQueryParameters {
    /**
     * Page number.
     */
    page?: number;
    /**
     * Items per page.
     */
    perPage?: number;
}
/**
 * Uri template for the request builder.
 */
export const Api_keysRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/agents/{agent_uu%2Did}/api_keys{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Api_keysRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Api_keysRequestBuilderNavigationMetadata: Record<Exclude<keyof Api_keysRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byApi_key_uuid: {
        requestsMetadata: WithApi_key_uuItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithApi_key_uuItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["api_key_uuid"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Api_keysRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Api_keysRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiListAgentAPIKeysOutputFromDiscriminatorValue,
        queryParametersMapper: Api_keysRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: Api_keysRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiCreateAgentAPIKeyOutputFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApiCreateAgentAPIKeyInputPublic,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
