/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreate_response_responseFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeCreate_response_request } from '../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const ResponsesRequestBuilderUriTemplate = "{+baseurl}/v1/responses";
/**
 * Metadata for all the requests in the request builder.
 */
export const ResponsesRequestBuilderRequestsMetadata = {
    post: {
        uriTemplate: ResponsesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createCreate_response_responseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreate_response_request,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
