/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MetadataRequestBuilderRequestsMetadata } from './metadata/index.js';
/**
 * Uri template for the request builder.
 */
export const WithApp_slugItemRequestBuilderUriTemplate = "{+baseurl}/v2/add-ons/apps/{app_slug}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithApp_slugItemRequestBuilderNavigationMetadata = {
    metadata: {
        requestsMetadata: MetadataRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
