/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDomainFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeDomain } from '../../../models/index.js';
// @ts-ignore
import { RecordsRequestBuilderNavigationMetadata, RecordsRequestBuilderRequestsMetadata } from './records/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithDomain_nameGetResponse}
 */
// @ts-ignore
export function createWithDomain_nameGetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoWithDomain_nameGetResponse;
}
/**
 * The deserialization information for the current model
 * @param WithDomain_nameGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithDomain_nameGetResponse(withDomain_nameGetResponse = {}) {
    return {
        "domain": n => { withDomain_nameGetResponse.domain = n.getObjectValue(createDomainFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithDomain_nameGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithDomain_nameGetResponse(writer, withDomain_nameGetResponse = {}, isSerializingDerivedType = false) {
    if (!withDomain_nameGetResponse || isSerializingDerivedType) {
        return;
    }
    writer.writeObjectValue("domain", withDomain_nameGetResponse.domain, serializeDomain);
    writer.writeAdditionalData(withDomain_nameGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const WithDomain_nameItemRequestBuilderUriTemplate = "{+baseurl}/v2/domains/{domain_name}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithDomain_nameItemRequestBuilderNavigationMetadata = {
    records: {
        requestsMetadata: RecordsRequestBuilderRequestsMetadata,
        navigationMetadata: RecordsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithDomain_nameItemRequestBuilderRequestsMetadata = {
    delete: {
        uriTemplate: WithDomain_nameItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithDomain_nameItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createWithDomain_nameGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
