/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiListModelCatalogOutputFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, type ApiListModelCatalogOutput, type ErrorEscaped } from '../../../../models/index.js';
// @ts-ignore
import { CatalogItemRequestBuilderRequestsMetadata, type CatalogItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/gen-ai/models/catalog
 */
export interface CatalogRequestBuilder extends BaseRequestBuilder<CatalogRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v2.genAi.modelsRequests.catalog.item collection
     * @param id Unique identifier of the item
     * @returns {CatalogItemRequestBuilder}
     */
     byId(id: string) : CatalogItemRequestBuilder;
    /**
     * Returns all available models.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiListModelCatalogOutput>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<CatalogRequestBuilderGetQueryParameters> | undefined) : Promise<ApiListModelCatalogOutput | undefined>;
    /**
     * Returns all available models.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CatalogRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Returns all available models.
 */
export interface CatalogRequestBuilderGetQueryParameters {
    limit?: number;
    page?: number;
}
/**
 * Uri template for the request builder.
 */
export const CatalogRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/models/catalog{?limit*,page*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CatalogRequestBuilderNavigationMetadata: Record<Exclude<keyof CatalogRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: CatalogItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CatalogRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CatalogRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiListModelCatalogOutputFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
