/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue } from '../../../../models/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MigratePutRequestBody}
 */
// @ts-ignore
export function createMigratePutRequestBodyFromDiscriminatorValue(parseNode) {
    return deserializeIntoMigratePutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param MigratePutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMigratePutRequestBody(migratePutRequestBody = {}) {
    return {
        "region": n => { migratePutRequestBody.region = n.getStringValue(); },
    };
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param MigratePutRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMigratePutRequestBody(writer, migratePutRequestBody = {}, isSerializingDerivedType = false) {
    if (!migratePutRequestBody || isSerializingDerivedType) {
        return;
    }
    writer.writeStringValue("region", migratePutRequestBody.region);
    writer.writeAdditionalData(migratePutRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const MigrateRequestBuilderUriTemplate = "{+baseurl}/v2/databases/{database_cluster_uuid}/migrate";
/**
 * Metadata for all the requests in the request builder.
 */
export const MigrateRequestBuilderRequestsMetadata = {
    put: {
        uriTemplate: MigrateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMigratePutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
