/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createFirewallFromDiscriminatorValue, createMeta_propertiesFromDiscriminatorValue, createPage_linksFromDiscriminatorValue, serializeFirewall, serializeMeta_properties, serializePage_links } from '../../models/index.js';
// @ts-ignore
import { WithFirewall_ItemRequestBuilderNavigationMetadata, WithFirewall_ItemRequestBuilderRequestsMetadata } from './item/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FirewallsGetResponse}
 */
// @ts-ignore
export function createFirewallsGetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoFirewallsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FirewallsPostResponse}
 */
// @ts-ignore
export function createFirewallsPostResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoFirewallsPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFirewallsGetResponse(firewallsGetResponse = {}) {
    return {
        "firewalls": n => { firewallsGetResponse.firewalls = n.getCollectionOfObjectValues(createFirewallFromDiscriminatorValue); },
        "links": n => { firewallsGetResponse.links = n.getObjectValue(createPage_linksFromDiscriminatorValue); },
        "meta": n => { firewallsGetResponse.meta = n.getObjectValue(createMeta_propertiesFromDiscriminatorValue); },
    };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFirewallsPostResponse(firewallsPostResponse = {}) {
    return {
        "firewall": n => { firewallsPostResponse.firewall = n.getObjectValue(createFirewallFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFirewallsGetResponse(writer, firewallsGetResponse = {}) {
    if (firewallsGetResponse) {
        writer.writeCollectionOfObjectValues("firewalls", firewallsGetResponse.firewalls, serializeFirewall);
        writer.writeObjectValue("links", firewallsGetResponse.links, serializePage_links);
        writer.writeObjectValue("meta", firewallsGetResponse.meta, serializeMeta_properties);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFirewallsPostResponse(writer, firewallsPostResponse = {}) {
    if (firewallsPostResponse) {
        writer.writeObjectValue("firewall", firewallsPostResponse.firewall, serializeFirewall);
    }
}
/**
 * Uri template for the request builder.
 */
export const FirewallsRequestBuilderUriTemplate = "{+baseurl}/v2/firewalls{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const FirewallsRequestBuilderGetQueryParametersMapper = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FirewallsRequestBuilderNavigationMetadata = {
    byFirewall_id: {
        requestsMetadata: WithFirewall_ItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithFirewall_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["firewall_id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const FirewallsRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: FirewallsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createFirewallsGetResponseFromDiscriminatorValue,
        queryParametersMapper: FirewallsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: FirewallsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue,
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createFirewallsPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFirewall,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
