/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createChat_completion_responseFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeChat_completion_request } from '../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const CompletionsRequestBuilderUriTemplate = "{+baseurl}/v1/chat/completions";
/**
 * Metadata for all the requests in the request builder.
 */
export const CompletionsRequestBuilderRequestsMetadata = {
    post: {
        uriTemplate: CompletionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createChat_completion_responseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeChat_completion_request,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
