/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, serializeDatabase_cluster_resize } from '../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const ResizeRequestBuilderUriTemplate = "{+baseurl}/v2/databases/{database_cluster_uuid}/resize";
/**
 * Metadata for all the requests in the request builder.
 */
export const ResizeRequestBuilderRequestsMetadata = {
    put: {
        uriTemplate: ResizeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDatabase_cluster_resize,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
