/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAlert_policyFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, createMeta_propertiesFromDiscriminatorValue, createPage_linksFromDiscriminatorValue, serializeAlert_policy, serializeAlert_policy_request, serializeMeta_properties, serializePage_links } from '../../../models/index.js';
// @ts-ignore
import { WithAlert_uuItemRequestBuilderRequestsMetadata } from './item/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AlertsGetResponse}
 */
// @ts-ignore
export function createAlertsGetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoAlertsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AlertsPostResponse}
 */
// @ts-ignore
export function createAlertsPostResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoAlertsPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAlertsGetResponse(alertsGetResponse = {}) {
    return {
        "links": n => { alertsGetResponse.links = n.getObjectValue(createPage_linksFromDiscriminatorValue); },
        "meta": n => { alertsGetResponse.meta = n.getObjectValue(createMeta_propertiesFromDiscriminatorValue); },
        "policies": n => { alertsGetResponse.policies = n.getCollectionOfObjectValues(createAlert_policyFromDiscriminatorValue); },
    };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAlertsPostResponse(alertsPostResponse = {}) {
    return {
        "policy": n => { alertsPostResponse.policy = n.getObjectValue(createAlert_policyFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAlertsGetResponse(writer, alertsGetResponse = {}) {
    if (alertsGetResponse) {
        writer.writeObjectValue("links", alertsGetResponse.links, serializePage_links);
        writer.writeObjectValue("meta", alertsGetResponse.meta, serializeMeta_properties);
        writer.writeCollectionOfObjectValues("policies", alertsGetResponse.policies, serializeAlert_policy);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAlertsPostResponse(writer, alertsPostResponse = {}) {
    if (alertsPostResponse) {
        writer.writeObjectValue("policy", alertsPostResponse.policy, serializeAlert_policy);
    }
}
/**
 * Uri template for the request builder.
 */
export const AlertsRequestBuilderUriTemplate = "{+baseurl}/v2/monitoring/alerts{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AlertsRequestBuilderGetQueryParametersMapper = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AlertsRequestBuilderNavigationMetadata = {
    byAlert_uuid: {
        requestsMetadata: WithAlert_uuItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["alert_uuid"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AlertsRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: AlertsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createAlertsGetResponseFromDiscriminatorValue,
        queryParametersMapper: AlertsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: AlertsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createAlertsPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAlert_policy_request,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
