/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createNeighbor_idsFromDiscriminatorValue, type ErrorEscaped, type Neighbor_ids } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/reports/droplet_neighbors_ids
 */
export interface Droplet_neighbors_idsRequestBuilder extends BaseRequestBuilder<Droplet_neighbors_idsRequestBuilder> {
    /**
     * To retrieve a list of all Droplets that are co-located on the same physicalhardware, send a GET request to `/v2/reports/droplet_neighbors_ids`.The results will be returned as a JSON object with a key of `neighbor_ids`.This will be set to an array of arrays. Each array will contain a set ofDroplet IDs for Droplets that share a physical server. An empty arrayindicates that all Droplets associated with your account are located onseparate physical hardware.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Neighbor_ids>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Neighbor_ids | undefined>;
    /**
     * To retrieve a list of all Droplets that are co-located on the same physicalhardware, send a GET request to `/v2/reports/droplet_neighbors_ids`.The results will be returned as a JSON object with a key of `neighbor_ids`.This will be set to an array of arrays. Each array will contain a set ofDroplet IDs for Droplets that share a physical server. An empty arrayindicates that all Droplets associated with your account are located onseparate physical hardware.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Droplet_neighbors_idsRequestBuilderUriTemplate = "{+baseurl}/v2/reports/droplet_neighbors_ids";
/**
 * Metadata for all the requests in the request builder.
 */
export const Droplet_neighbors_idsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Droplet_neighbors_idsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createNeighbor_idsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
