/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createMetricsFromDiscriminatorValue } from '../../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const Filesystem_sizeRequestBuilderUriTemplate = "{+baseurl}/v2/monitoring/metrics/droplet/filesystem_size?end={end}&host_id={host_id}&start={start}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Filesystem_sizeRequestBuilderGetQueryParametersMapper = {
    "hostId": "host_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Filesystem_sizeRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: Filesystem_sizeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createMetricsFromDiscriminatorValue,
        queryParametersMapper: Filesystem_sizeRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
