/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createMeta_propertiesFromDiscriminatorValue, createPage_linksFromDiscriminatorValue, createVolumeActionFromDiscriminatorValue, deserializeIntoVolume_action_post_attach, deserializeIntoVolume_action_post_detach, deserializeIntoVolume_action_post_resize, serializeMeta_properties, serializePage_links, serializeVolume_action_post_attach, serializeVolume_action_post_detach, serializeVolume_action_post_resize, serializeVolumeAction } from '../../../../models/index.js';
// @ts-ignore
import { WithAction_ItemRequestBuilderRequestsMetadata } from './item/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActionsGetResponse}
 */
// @ts-ignore
export function createActionsGetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoActionsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Volume_action_post_attach | Volume_action_post_detach | Volume_action_post_resize}
 */
// @ts-ignore
export function createActionsPostRequestBodyFromDiscriminatorValue(parseNode) {
    return deserializeIntoActionsPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActionsPostResponse}
 */
// @ts-ignore
export function createActionsPostResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoActionsPostResponse;
}
/**
 * The deserialization information for the current model
 * @param ActionsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActionsGetResponse(actionsGetResponse = {}) {
    return {
        "actions": n => { actionsGetResponse.actions = n.getCollectionOfObjectValues(createVolumeActionFromDiscriminatorValue); },
        "links": n => { actionsGetResponse.links = n.getObjectValue(createPage_linksFromDiscriminatorValue); },
        "meta": n => { actionsGetResponse.meta = n.getObjectValue(createMeta_propertiesFromDiscriminatorValue); },
    };
}
/**
 * The deserialization information for the current model
 * @param ActionsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActionsPostRequestBody(actionsPostRequestBody = {}) {
    return {
        ...deserializeIntoVolume_action_post_attach(actionsPostRequestBody),
        ...deserializeIntoVolume_action_post_detach(actionsPostRequestBody),
        ...deserializeIntoVolume_action_post_resize(actionsPostRequestBody),
    };
}
/**
 * The deserialization information for the current model
 * @param ActionsPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActionsPostResponse(actionsPostResponse = {}) {
    return {
        "action": n => { actionsPostResponse.action = n.getObjectValue(createVolumeActionFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param ActionsGetResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActionsGetResponse(writer, actionsGetResponse = {}, isSerializingDerivedType = false) {
    if (!actionsGetResponse || isSerializingDerivedType) {
        return;
    }
    writer.writeCollectionOfObjectValues("actions", actionsGetResponse.actions, serializeVolumeAction);
    writer.writeObjectValue("links", actionsGetResponse.links, serializePage_links);
    writer.writeObjectValue("meta", actionsGetResponse.meta, serializeMeta_properties);
    writer.writeAdditionalData(actionsGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param ActionsPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActionsPostRequestBody(writer, actionsPostRequestBody = {}, isSerializingDerivedType = false) {
    serializeVolume_action_post_attach(writer, actionsPostRequestBody);
    serializeVolume_action_post_detach(writer, actionsPostRequestBody);
    serializeVolume_action_post_resize(writer, actionsPostRequestBody);
}
/**
 * Serializes information the current object
 * @param ActionsPostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActionsPostResponse(writer, actionsPostResponse = {}, isSerializingDerivedType = false) {
    if (!actionsPostResponse || isSerializingDerivedType) {
        return;
    }
    writer.writeObjectValue("action", actionsPostResponse.action, serializeVolumeAction);
    writer.writeAdditionalData(actionsPostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ActionsRequestBuilderUriTemplate = "{+baseurl}/v2/volumes/{volume_id}/actions{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ActionsRequestBuilderGetQueryParametersMapper = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ActionsRequestBuilderNavigationMetadata = {
    byAction_id: {
        requestsMetadata: WithAction_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["action_id"],
    },
};
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ActionsRequestBuilderPostQueryParametersMapper = {
    "perPage": "per_page",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ActionsRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: ActionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createActionsGetResponseFromDiscriminatorValue,
        queryParametersMapper: ActionsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: ActionsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createActionsPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeActionsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
        queryParametersMapper: ActionsRequestBuilderPostQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
