/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue } from '../../../../../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const WithNode_ItemRequestBuilderUriTemplate = "{+baseurl}/v2/kubernetes/clusters/{cluster_id}/node_pools/{node_pool_id}/nodes/{node_id}{?replace*,skip_drain*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const WithNode_ItemRequestBuilderDeleteQueryParametersMapper = {
    "skipDrain": "skip_drain",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithNode_ItemRequestBuilderRequestsMetadata = {
    delete: {
        uriTemplate: WithNode_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
        queryParametersMapper: WithNode_ItemRequestBuilderDeleteQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
