/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { WithFinding_uuItemRequestBuilderNavigationMetadata } from './item/index.js';
/**
 * Uri template for the request builder.
 */
export const FindingsRequestBuilderUriTemplate = "{+baseurl}/v2/security/scans/{scan_id}/findings";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FindingsRequestBuilderNavigationMetadata = {
    byFinding_uuid: {
        navigationMetadata: WithFinding_uuItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["finding_uuid"],
    },
};
/* tslint:enable */
/* eslint-enable */
