/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createScanFromDiscriminatorValue, serializeScan, type ErrorEscaped, type Scan } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LatestGetResponse}
 */
// @ts-ignore
export function createLatestGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLatestGetResponse;
}
/**
 * The deserialization information for the current model
 * @param LatestGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLatestGetResponse(latestGetResponse: Partial<LatestGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "scan": n => { latestGetResponse.scan = n.getObjectValue<Scan>(createScanFromDiscriminatorValue); },
    }
}
export type GetSeverityQueryParameterType = (typeof GetSeverityQueryParameterTypeObject)[keyof typeof GetSeverityQueryParameterTypeObject];
export interface LatestGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The scan property
     */
    scan?: Scan | null;
}
/**
 * Builds and executes requests for operations under /v2/security/scans/latest
 */
export interface LatestRequestBuilder extends BaseRequestBuilder<LatestRequestBuilder> {
    /**
     * To get the latest CSPM scan, send a GET request to `/v2/security/scans/latest`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<LatestGetResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<LatestRequestBuilderGetQueryParameters> | undefined) : Promise<LatestGetResponse | undefined>;
    /**
     * To get the latest CSPM scan, send a GET request to `/v2/security/scans/latest`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LatestRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * To get the latest CSPM scan, send a GET request to `/v2/security/scans/latest`.
 */
export interface LatestRequestBuilderGetQueryParameters {
    /**
     * Which 'page' of paginated results to return.
     */
    page?: number;
    /**
     * Number of items returned per page
     */
    perPage?: number;
    /**
     * The finding severity level to include.
     */
    severity?: GetSeverityQueryParameterType;
    /**
     * The finding type to include.
     */
    type?: string;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LatestGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLatestGetResponse(writer: SerializationWriter, latestGetResponse: Partial<LatestGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!latestGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Scan>("scan", latestGetResponse.scan, serializeScan);
    writer.writeAdditionalData(latestGetResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const LatestRequestBuilderUriTemplate = "{+baseurl}/v2/security/scans/latest{?page*,per_page*,severity*,type*}";
export const GetSeverityQueryParameterTypeObject = {
    LOW: "LOW",
    MEDIUM: "MEDIUM",
    HIGH: "HIGH",
    CRITICAL: "CRITICAL",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const LatestRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "perPage": "per_page",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LatestRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LatestRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createLatestGetResponseFromDiscriminatorValue,
        queryParametersMapper: LatestRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
