/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { KeysRequestBuilderNavigationMetadata, KeysRequestBuilderRequestsMetadata } from './keys/index.js';
/**
 * Uri template for the request builder.
 */
export const SpacesRequestBuilderUriTemplate = "{+baseurl}/v2/spaces";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SpacesRequestBuilderNavigationMetadata = {
    keys: {
        requestsMetadata: KeysRequestBuilderRequestsMetadata,
        navigationMetadata: KeysRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
