/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createMetricsFromDiscriminatorValue } from '../../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const Load_1RequestBuilderUriTemplate = "{+baseurl}/v2/monitoring/metrics/droplet/load_1?end={end}&host_id={host_id}&start={start}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Load_1RequestBuilderGetQueryParametersMapper = {
    "hostId": "host_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Load_1RequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: Load_1RequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createMetricsFromDiscriminatorValue,
        queryParametersMapper: Load_1RequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
