/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { WithJob_nameItemRequestBuilderNavigationMetadata } from './item/index.js';
/**
 * Uri template for the request builder.
 */
export const JobsRequestBuilderUriTemplate = "{+baseurl}/v2/apps/{app_%2Did}/jobs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobsRequestBuilderNavigationMetadata = {
    byJob_name: {
        navigationMetadata: WithJob_nameItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["job_name"],
    },
};
/* tslint:enable */
/* eslint-enable */
