/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createTagsFromDiscriminatorValue, serializeTags } from '../../../models/index.js';
// @ts-ignore
import { ResourcesRequestBuilderRequestsMetadata } from './resources/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithTag_GetResponse}
 */
// @ts-ignore
export function createWithTag_GetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoWithTag_GetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithTag_GetResponse(withTag_GetResponse = {}) {
    return {
        "tag": n => { withTag_GetResponse.tag = n.getObjectValue(createTagsFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithTag_GetResponse(writer, withTag_GetResponse = {}) {
    if (withTag_GetResponse) {
        writer.writeObjectValue("tag", withTag_GetResponse.tag, serializeTags);
    }
}
/**
 * Uri template for the request builder.
 */
export const WithTag_ItemRequestBuilderUriTemplate = "{+baseurl}/v2/tags/{tag_id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTag_ItemRequestBuilderNavigationMetadata = {
    resources: {
        requestsMetadata: ResourcesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTag_ItemRequestBuilderRequestsMetadata = {
    delete: {
        uriTemplate: WithTag_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithTag_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createWithTag_GetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
