/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAddons_resourceFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeAddons_resource } from '../../../../../models/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PlanPatchRequestBody}
 */
// @ts-ignore
export function createPlanPatchRequestBodyFromDiscriminatorValue(parseNode) {
    return deserializeIntoPlanPatchRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PlanPatchResponse}
 */
// @ts-ignore
export function createPlanPatchResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoPlanPatchResponse;
}
/**
 * The deserialization information for the current model
 * @param PlanPatchRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPlanPatchRequestBody(planPatchRequestBody = {}) {
    return {
        "plan_slug": n => { planPatchRequestBody.planSlug = n.getStringValue(); },
    };
}
/**
 * The deserialization information for the current model
 * @param PlanPatchResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPlanPatchResponse(planPatchResponse = {}) {
    return {
        "resource": n => { planPatchResponse.resource = n.getObjectValue(createAddons_resourceFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PlanPatchRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePlanPatchRequestBody(writer, planPatchRequestBody = {}, isSerializingDerivedType = false) {
    if (!planPatchRequestBody || isSerializingDerivedType) {
        return;
    }
    writer.writeStringValue("plan_slug", planPatchRequestBody.planSlug);
    writer.writeAdditionalData(planPatchRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PlanPatchResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePlanPatchResponse(writer, planPatchResponse = {}, isSerializingDerivedType = false) {
    if (!planPatchResponse || isSerializingDerivedType) {
        return;
    }
    writer.writeObjectValue("resource", planPatchResponse.resource, serializeAddons_resource);
    writer.writeAdditionalData(planPatchResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const PlanRequestBuilderUriTemplate = "{+baseurl}/v2/add-ons/saas/{resource_uuid}/plan";
/**
 * Metadata for all the requests in the request builder.
 */
export const PlanRequestBuilderRequestsMetadata = {
    patch: {
        uriTemplate: PlanRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createPlanPatchResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePlanPatchRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
