/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiCreateAnthropicAPIKeyOutputFromDiscriminatorValue, createApiListAnthropicAPIKeysOutputFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeApiCreateAnthropicAPIKeyInputPublic } from '../../../../models/index.js';
// @ts-ignore
import { Api_key_uuItemRequestBuilderNavigationMetadata, Api_key_uuItemRequestBuilderRequestsMetadata } from './item/index.js';
/**
 * Uri template for the request builder.
 */
export const KeysRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/anthropic/keys{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const KeysRequestBuilderGetQueryParametersMapper = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const KeysRequestBuilderNavigationMetadata = {
    byApi_key_uuId: {
        requestsMetadata: Api_key_uuItemRequestBuilderRequestsMetadata,
        navigationMetadata: Api_key_uuItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["api_key_uu%2Did"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const KeysRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: KeysRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createApiListAnthropicAPIKeysOutputFromDiscriminatorValue,
        queryParametersMapper: KeysRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: KeysRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createApiCreateAnthropicAPIKeyOutputFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApiCreateAnthropicAPIKeyInputPublic,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
