/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createReserved_ipFromDiscriminatorValue, serializeReserved_ip } from '../../../models/index.js';
// @ts-ignore
import { ActionsRequestBuilderNavigationMetadata, ActionsRequestBuilderRequestsMetadata } from './actions/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithReserved_ipGetResponse}
 */
// @ts-ignore
export function createWithReserved_ipGetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoWithReserved_ipGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithReserved_ipGetResponse(withReserved_ipGetResponse = {}) {
    return {
        "reserved_ip": n => { withReserved_ipGetResponse.reservedIp = n.getObjectValue(createReserved_ipFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithReserved_ipGetResponse(writer, withReserved_ipGetResponse = {}) {
    if (withReserved_ipGetResponse) {
        writer.writeObjectValue("reserved_ip", withReserved_ipGetResponse.reservedIp, serializeReserved_ip);
    }
}
/**
 * Uri template for the request builder.
 */
export const WithReserved_ipItemRequestBuilderUriTemplate = "{+baseurl}/v2/reserved_ips/{reserved_ip}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithReserved_ipItemRequestBuilderNavigationMetadata = {
    actions: {
        requestsMetadata: ActionsRequestBuilderRequestsMetadata,
        navigationMetadata: ActionsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithReserved_ipItemRequestBuilderRequestsMetadata = {
    delete: {
        uriTemplate: WithReserved_ipItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithReserved_ipItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createWithReserved_ipGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
