/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDo_settingsFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeDo_settings, type Do_settings, type ErrorEscaped } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Do_settingsGetResponse}
 */
// @ts-ignore
export function createDo_settingsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDo_settingsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Do_settingsPutRequestBody}
 */
// @ts-ignore
export function createDo_settingsPutRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDo_settingsPutRequestBody;
}
/**
 * The deserialization information for the current model
 * @param Do_settingsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDo_settingsGetResponse(do_settingsGetResponse: Partial<Do_settingsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "do_settings": n => { do_settingsGetResponse.doSettings = n.getObjectValue<Do_settings>(createDo_settingsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param Do_settingsPutRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDo_settingsPutRequestBody(do_settingsPutRequestBody: Partial<Do_settingsPutRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "do_settings": n => { do_settingsPutRequestBody.doSettings = n.getObjectValue<Do_settings>(createDo_settingsFromDiscriminatorValue); },
    }
}
export interface Do_settingsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * DigitalOcean-specific settings for the database cluster.
     */
    doSettings?: Do_settings | null;
}
export interface Do_settingsPutRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * DigitalOcean-specific settings for the database cluster.
     */
    doSettings?: Do_settings | null;
}
/**
 * Builds and executes requests for operations under /v2/databases/{database_cluster_uuid}/do_settings
 */
export interface Do_settingsRequestBuilder extends BaseRequestBuilder<Do_settingsRequestBuilder> {
    /**
     * To retrieve the DigitalOcean-specific settings for a database cluster, send a GET request to `/v2/databases/$DATABASE_ID/do_settings`.The response will include the current `service_cnames` configuration.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Do_settingsGetResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Do_settingsGetResponse | undefined>;
    /**
     * To update the DigitalOcean-specific settings for a database cluster, send a PUT request to `/v2/databases/$DATABASE_ID/do_settings`.Currently, the only supported setting is `service_cnames`, which allows you to specify custom DNS names (CNAMEs) to be included in the TLS certificate Subject Alternative Names (SANs) for the database cluster nodes. This enables TLS verification when connecting via a custom hostname.After updating, the database nodes will be replaced to apply the new certificate. This process is performed as a rolling replacement and does not cause downtime.To clear all custom CNAMEs, send an empty array or omit the field.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 422 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     put(body: Do_settingsPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * To retrieve the DigitalOcean-specific settings for a database cluster, send a GET request to `/v2/databases/$DATABASE_ID/do_settings`.The response will include the current `service_cnames` configuration.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * To update the DigitalOcean-specific settings for a database cluster, send a PUT request to `/v2/databases/$DATABASE_ID/do_settings`.Currently, the only supported setting is `service_cnames`, which allows you to specify custom DNS names (CNAMEs) to be included in the TLS certificate Subject Alternative Names (SANs) for the database cluster nodes. This enables TLS verification when connecting via a custom hostname.After updating, the database nodes will be replaced to apply the new certificate. This process is performed as a rolling replacement and does not cause downtime.To clear all custom CNAMEs, send an empty array or omit the field.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: Do_settingsPutRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param Do_settingsGetResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDo_settingsGetResponse(writer: SerializationWriter, do_settingsGetResponse: Partial<Do_settingsGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!do_settingsGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Do_settings>("do_settings", do_settingsGetResponse.doSettings, serializeDo_settings);
    writer.writeAdditionalData(do_settingsGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param Do_settingsPutRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDo_settingsPutRequestBody(writer: SerializationWriter, do_settingsPutRequestBody: Partial<Do_settingsPutRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!do_settingsPutRequestBody || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Do_settings>("do_settings", do_settingsPutRequestBody.doSettings, serializeDo_settings);
    writer.writeAdditionalData(do_settingsPutRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const Do_settingsRequestBuilderUriTemplate = "{+baseurl}/v2/databases/{database_cluster_uuid}/do_settings";
/**
 * Metadata for all the requests in the request builder.
 */
export const Do_settingsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Do_settingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDo_settingsGetResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: Do_settingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            422: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDo_settingsPutRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
