/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiListAgentsByWorkspaceOutputFromDiscriminatorValue, createApiMoveAgentsToWorkspaceOutputFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeApiMoveAgentsToWorkspaceInputPublic, serializeApiMoveAgentsToWorkspaceOutput, type ApiListAgentsByWorkspaceOutput, type ApiMoveAgentsToWorkspaceInputPublic, type ApiMoveAgentsToWorkspaceOutput, type ErrorEscaped } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/gen-ai/workspaces/{workspace_uuid}/agents
 */
export interface AgentsRequestBuilder extends BaseRequestBuilder<AgentsRequestBuilder> {
    /**
     * To list all agents by a Workspace, send a GET request to `/v2/gen-ai/workspaces/{workspace_uuid}/agents`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiListAgentsByWorkspaceOutput>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<AgentsRequestBuilderGetQueryParameters> | undefined) : Promise<ApiListAgentsByWorkspaceOutput | undefined>;
    /**
     * To move all listed agents a given workspace, send a PUT request to `/v2/gen-ai/workspaces/{workspace_uuid}/agents`.
     * @param body Parameters for Moving agents to a Workspace
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiMoveAgentsToWorkspaceOutput>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     put(body: ApiMoveAgentsToWorkspaceInputPublic, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApiMoveAgentsToWorkspaceOutput | undefined>;
    /**
     * To list all agents by a Workspace, send a GET request to `/v2/gen-ai/workspaces/{workspace_uuid}/agents`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AgentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * To move all listed agents a given workspace, send a PUT request to `/v2/gen-ai/workspaces/{workspace_uuid}/agents`.
     * @param body Parameters for Moving agents to a Workspace
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ApiMoveAgentsToWorkspaceInputPublic, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * To list all agents by a Workspace, send a GET request to `/v2/gen-ai/workspaces/{workspace_uuid}/agents`.
 */
export interface AgentsRequestBuilderGetQueryParameters {
    /**
     * Only list agents that are deployed.
     */
    onlyDeployed?: boolean;
    /**
     * Page number.
     */
    page?: number;
    /**
     * Items per page.
     */
    perPage?: number;
}
/**
 * Uri template for the request builder.
 */
export const AgentsRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/workspaces/{workspace_uuid}/agents{?only_deployed*,page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AgentsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "onlyDeployed": "only_deployed",
    "perPage": "per_page",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AgentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AgentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiListAgentsByWorkspaceOutputFromDiscriminatorValue,
        queryParametersMapper: AgentsRequestBuilderGetQueryParametersMapper,
    },
    put: {
        uriTemplate: AgentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiMoveAgentsToWorkspaceOutputFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApiMoveAgentsToWorkspaceInputPublic,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
