/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createMetricsFromDiscriminatorValue, type ErrorEscaped, type Metrics } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p
 */
export interface Droplets_http_session_duration_50pRequestBuilder extends BaseRequestBuilder<Droplets_http_session_duration_50pRequestBuilder> {
    /**
     * To retrieve Droplets 50th percentile HTTP session duration in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Metrics>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<Droplets_http_session_duration_50pRequestBuilderGetQueryParameters> | undefined) : Promise<Metrics | undefined>;
    /**
     * To retrieve Droplets 50th percentile HTTP session duration in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<Droplets_http_session_duration_50pRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * To retrieve Droplets 50th percentile HTTP session duration in seconds for a given load balancer, send a GET request to `/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p`.
 */
export interface Droplets_http_session_duration_50pRequestBuilderGetQueryParameters {
    /**
     * UNIX timestamp to end metric window.
     */
    end?: string;
    /**
     * A unique identifier for a load balancer.
     */
    lbId?: string;
    /**
     * UNIX timestamp to start metric window.
     */
    start?: string;
}
/**
 * Uri template for the request builder.
 */
export const Droplets_http_session_duration_50pRequestBuilderUriTemplate = "{+baseurl}/v2/monitoring/metrics/load_balancer/droplets_http_session_duration_50p?end={end}&lb_id={lb_id}&start={start}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Droplets_http_session_duration_50pRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "lbId": "lb_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Droplets_http_session_duration_50pRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: Droplets_http_session_duration_50pRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMetricsFromDiscriminatorValue,
        queryParametersMapper: Droplets_http_session_duration_50pRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
