/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createForwarding_ruleFromDiscriminatorValue, serializeForwarding_rule, type ErrorEscaped, type Forwarding_rule } from '../../../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Forwarding_rulesDeleteRequestBody}
 */
// @ts-ignore
export function createForwarding_rulesDeleteRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoForwarding_rulesDeleteRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Forwarding_rulesPostRequestBody}
 */
// @ts-ignore
export function createForwarding_rulesPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoForwarding_rulesPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param Forwarding_rulesDeleteRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoForwarding_rulesDeleteRequestBody(forwarding_rulesDeleteRequestBody: Partial<Forwarding_rulesDeleteRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "forwarding_rules": n => { forwarding_rulesDeleteRequestBody.forwardingRules = n.getCollectionOfObjectValues<Forwarding_rule>(createForwarding_ruleFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param Forwarding_rulesPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoForwarding_rulesPostRequestBody(forwarding_rulesPostRequestBody: Partial<Forwarding_rulesPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "forwarding_rules": n => { forwarding_rulesPostRequestBody.forwardingRules = n.getCollectionOfObjectValues<Forwarding_rule>(createForwarding_ruleFromDiscriminatorValue); },
    }
}
export interface Forwarding_rulesDeleteRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The forwarding_rules property
     */
    forwardingRules?: Forwarding_rule[] | null;
}
export interface Forwarding_rulesPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The forwarding_rules property
     */
    forwardingRules?: Forwarding_rule[] | null;
}
/**
 * Builds and executes requests for operations under /v2/load_balancers/{lb_id}/forwarding_rules
 */
export interface Forwarding_rulesRequestBuilder extends BaseRequestBuilder<Forwarding_rulesRequestBuilder> {
    /**
     * To remove forwarding rules from a load balancer instance, send a DELETErequest to `/v2/load_balancers/$LOAD_BALANCER_ID/forwarding_rules`. In thebody of the request, there should be a `forwarding_rules` attribute containingan array of rules to be removed.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     delete(body: Forwarding_rulesDeleteRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * To add an additional forwarding rule to a load balancer instance, send a POSTrequest to `/v2/load_balancers/$LOAD_BALANCER_ID/forwarding_rules`. In the bodyof the request, there should be a `forwarding_rules` attribute containing anarray of rules to be added.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     post(body: Forwarding_rulesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * To remove forwarding rules from a load balancer instance, send a DELETErequest to `/v2/load_balancers/$LOAD_BALANCER_ID/forwarding_rules`. In thebody of the request, there should be a `forwarding_rules` attribute containingan array of rules to be removed.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(body: Forwarding_rulesDeleteRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * To add an additional forwarding rule to a load balancer instance, send a POSTrequest to `/v2/load_balancers/$LOAD_BALANCER_ID/forwarding_rules`. In the bodyof the request, there should be a `forwarding_rules` attribute containing anarray of rules to be added.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Forwarding_rulesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param Forwarding_rulesDeleteRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeForwarding_rulesDeleteRequestBody(writer: SerializationWriter, forwarding_rulesDeleteRequestBody: Partial<Forwarding_rulesDeleteRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!forwarding_rulesDeleteRequestBody || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Forwarding_rule>("forwarding_rules", forwarding_rulesDeleteRequestBody.forwardingRules, serializeForwarding_rule);
    writer.writeAdditionalData(forwarding_rulesDeleteRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param Forwarding_rulesPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeForwarding_rulesPostRequestBody(writer: SerializationWriter, forwarding_rulesPostRequestBody: Partial<Forwarding_rulesPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!forwarding_rulesPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Forwarding_rule>("forwarding_rules", forwarding_rulesPostRequestBody.forwardingRules, serializeForwarding_rule);
    writer.writeAdditionalData(forwarding_rulesPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const Forwarding_rulesRequestBuilderUriTemplate = "{+baseurl}/v2/load_balancers/{lb_id}/forwarding_rules";
/**
 * Metadata for all the requests in the request builder.
 */
export const Forwarding_rulesRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: Forwarding_rulesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeForwarding_rulesDeleteRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
    post: {
        uriTemplate: Forwarding_rulesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeForwarding_rulesPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
