/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDocker_credentialsFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue } from '../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const DockerCredentialsRequestBuilderUriTemplate = "{+baseurl}/v2/registries/{registry_name}/docker-credentials";
/**
 * Metadata for all the requests in the request builder.
 */
export const DockerCredentialsRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: DockerCredentialsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createDocker_credentialsFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
