/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { KeysRequestBuilderNavigationMetadata, KeysRequestBuilderRequestsMetadata, type KeysRequestBuilder } from './keys/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/gen-ai/anthropic
 */
export interface AnthropicRequestBuilder extends BaseRequestBuilder<AnthropicRequestBuilder> {
    /**
     * The keys property
     */
    get keys(): KeysRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AnthropicRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/anthropic";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnthropicRequestBuilderNavigationMetadata: Record<Exclude<keyof AnthropicRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    keys: {
        requestsMetadata: KeysRequestBuilderRequestsMetadata,
        navigationMetadata: KeysRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
