/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { KeysRequestBuilderNavigationMetadata, KeysRequestBuilderRequestsMetadata } from './keys/index.js';
/**
 * Uri template for the request builder.
 */
export const AnthropicRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/anthropic";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AnthropicRequestBuilderNavigationMetadata = {
    keys: {
        requestsMetadata: KeysRequestBuilderRequestsMetadata,
        navigationMetadata: KeysRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
