/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiUpdateAgentDeploymentVisbilityOutputFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeApiUpdateAgentDeploymentVisbilityOutput, serializeApiUpdateAgentDeploymentVisibilityInputPublic, type ApiUpdateAgentDeploymentVisbilityOutput, type ApiUpdateAgentDeploymentVisibilityInputPublic, type ErrorEscaped } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/gen-ai/agents/{agent_uu-id}/deployment_visibility
 */
export interface Deployment_visibilityRequestBuilder extends BaseRequestBuilder<Deployment_visibilityRequestBuilder> {
    /**
     * Check whether an agent is public or private. To update the agent status, send a PUT request to `/v2/gen-ai/agents/{uuid}/deployment_visibility`.
     * @param body UpdateAgentDeploymentVisibilityInputPublic description
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ApiUpdateAgentDeploymentVisbilityOutput>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     put(body: ApiUpdateAgentDeploymentVisibilityInputPublic, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ApiUpdateAgentDeploymentVisbilityOutput | undefined>;
    /**
     * Check whether an agent is public or private. To update the agent status, send a PUT request to `/v2/gen-ai/agents/{uuid}/deployment_visibility`.
     * @param body UpdateAgentDeploymentVisibilityInputPublic description
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: ApiUpdateAgentDeploymentVisibilityInputPublic, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Deployment_visibilityRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/agents/{agent_uu%2Did}/deployment_visibility";
/**
 * Metadata for all the requests in the request builder.
 */
export const Deployment_visibilityRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: Deployment_visibilityRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createApiUpdateAgentDeploymentVisbilityOutputFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApiUpdateAgentDeploymentVisibilityInputPublic,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
