/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApiGenerateOauth2URLOutputFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue } from '../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const UrlRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/oauth2/url{?redirect_url*,type*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const UrlRequestBuilderGetQueryParametersMapper = {
    "redirectUrl": "redirect_url",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UrlRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: UrlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createApiGenerateOauth2URLOutputFromDiscriminatorValue,
        queryParametersMapper: UrlRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
