/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { WithKnowledge_base_uuItemRequestBuilderRequestsMetadata } from './item/index.js';
/**
 * Uri template for the request builder.
 */
export const KnowledgeBaseRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai/scheduled-indexing/knowledge-base";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const KnowledgeBaseRequestBuilderNavigationMetadata = {
    byKnowledge_base_uuid: {
        requestsMetadata: WithKnowledge_base_uuItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["knowledge_base_uuid"],
    },
};
/* tslint:enable */
/* eslint-enable */
