/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithNode_ItemRequestBuilder, WithNode_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/kubernetes/clusters/{cluster_id}/node_pools/{node_pool_id}/nodes
 */
export interface NodesRequestBuilder extends BaseRequestBuilder<NodesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v2.kubernetes.clusters.item.node_pools.item.nodes.item collection
     * @param node_id A unique ID that can be used to reference a node in a Kubernetes node pool.
     * @returns {WithNode_ItemRequestBuilder}
     */
     byNode_id(node_id: Guid) : WithNode_ItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const NodesRequestBuilderUriTemplate = "{+baseurl}/v2/kubernetes/clusters/{cluster_id}/node_pools/{node_pool_id}/nodes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NodesRequestBuilderNavigationMetadata: Record<Exclude<keyof NodesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byNode_id: {
        requestsMetadata: WithNode_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["node_id"],
    },
};
/* tslint:enable */
/* eslint-enable */
