/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createNfs_snapshot_get_responseFromDiscriminatorValue } from '../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const WithNfs_snapshot_ItemRequestBuilderUriTemplate = "{+baseurl}/v2/nfs/snapshots/{nfs_snapshot_id}{?region*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithNfs_snapshot_ItemRequestBuilderRequestsMetadata = {
    delete: {
        uriTemplate: WithNfs_snapshot_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithNfs_snapshot_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createNfs_snapshot_get_responseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
