/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, serializeLoad_balancer_droplet_ids, type ErrorEscaped, type Load_balancer_droplet_ids } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/load_balancers/{lb_id}/droplets
 */
export interface DropletsRequestBuilder extends BaseRequestBuilder<DropletsRequestBuilder> {
    /**
     * To remove a Droplet from a load balancer instance, send a DELETE request to`/v2/load_balancers/$LOAD_BALANCER_ID/droplets`. In the body of the request,there should be a `droplet_ids` attribute containing a list of Droplet IDs.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     delete(body: Load_balancer_droplet_ids, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * To assign a Droplet to a load balancer instance, send a POST request to`/v2/load_balancers/$LOAD_BALANCER_ID/droplets`. In the body of the request,there should be a `droplet_ids` attribute containing a list of Droplet IDs.Individual Droplets can not be added to a load balancer configured with aDroplet tag. Attempting to do so will result in a "422 Unprocessable Entity"response from the API.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 404 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     post(body: Load_balancer_droplet_ids, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * To remove a Droplet from a load balancer instance, send a DELETE request to`/v2/load_balancers/$LOAD_BALANCER_ID/droplets`. In the body of the request,there should be a `droplet_ids` attribute containing a list of Droplet IDs.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(body: Load_balancer_droplet_ids, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * To assign a Droplet to a load balancer instance, send a POST request to`/v2/load_balancers/$LOAD_BALANCER_ID/droplets`. In the body of the request,there should be a `droplet_ids` attribute containing a list of Droplet IDs.Individual Droplets can not be added to a load balancer configured with aDroplet tag. Attempting to do so will result in a "422 Unprocessable Entity"response from the API.No response body will be sent back, but the response code will indicatesuccess. Specifically, the response code will be a 204, which means that theaction was successful with no returned body data.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Load_balancer_droplet_ids, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DropletsRequestBuilderUriTemplate = "{+baseurl}/v2/load_balancers/{lb_id}/droplets";
/**
 * Metadata for all the requests in the request builder.
 */
export const DropletsRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: DropletsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLoad_balancer_droplet_ids,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
    post: {
        uriTemplate: DropletsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeLoad_balancer_droplet_ids,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
