/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Bandwidth_dailyRequestBuilderRequestsMetadata } from './bandwidth_daily/index.js';
/**
 * Uri template for the request builder.
 */
export const MetricsRequestBuilderUriTemplate = "{+baseurl}/v2/apps/{app_%2Did}/metrics";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MetricsRequestBuilderNavigationMetadata = {
    bandwidth_daily: {
        requestsMetadata: Bandwidth_dailyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
