/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AgentsRequestBuilderNavigationMetadata, AgentsRequestBuilderRequestsMetadata, type AgentsRequestBuilder } from './agents/index.js';
// @ts-ignore
import { AnthropicRequestBuilderNavigationMetadata, type AnthropicRequestBuilder } from './anthropic/index.js';
// @ts-ignore
import { Indexing_jobsRequestBuilderNavigationMetadata, Indexing_jobsRequestBuilderRequestsMetadata, type Indexing_jobsRequestBuilder } from './indexing_jobs/index.js';
// @ts-ignore
import { Knowledge_basesRequestBuilderNavigationMetadata, Knowledge_basesRequestBuilderRequestsMetadata, type Knowledge_basesRequestBuilder } from './knowledge_bases/index.js';
// @ts-ignore
import { ModelsRequestBuilderRequestsMetadata, type ModelsRequestBuilder } from './modelsRequests/index.js';
// @ts-ignore
import { RegionsRequestBuilderRequestsMetadata, type RegionsRequestBuilder } from './regions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/gen-ai
 */
export interface GenAiRequestBuilder extends BaseRequestBuilder<GenAiRequestBuilder> {
    /**
     * The agents property
     */
    get agents(): AgentsRequestBuilder;
    /**
     * The anthropic property
     */
    get anthropic(): AnthropicRequestBuilder;
    /**
     * The indexing_jobs property
     */
    get indexing_jobs(): Indexing_jobsRequestBuilder;
    /**
     * The knowledge_bases property
     */
    get knowledge_bases(): Knowledge_basesRequestBuilder;
    /**
     * The models property
     */
    get models(): ModelsRequestBuilder;
    /**
     * The regions property
     */
    get regions(): RegionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GenAiRequestBuilderUriTemplate = "{+baseurl}/v2/gen-ai";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GenAiRequestBuilderNavigationMetadata: Record<Exclude<keyof GenAiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    agents: {
        requestsMetadata: AgentsRequestBuilderRequestsMetadata,
        navigationMetadata: AgentsRequestBuilderNavigationMetadata,
    },
    anthropic: {
        navigationMetadata: AnthropicRequestBuilderNavigationMetadata,
    },
    indexing_jobs: {
        requestsMetadata: Indexing_jobsRequestBuilderRequestsMetadata,
        navigationMetadata: Indexing_jobsRequestBuilderNavigationMetadata,
    },
    knowledge_bases: {
        requestsMetadata: Knowledge_basesRequestBuilderRequestsMetadata,
        navigationMetadata: Knowledge_basesRequestBuilderNavigationMetadata,
    },
    models: {
        requestsMetadata: ModelsRequestBuilderRequestsMetadata,
    },
    regions: {
        requestsMetadata: RegionsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
