/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ChecksRequestBuilderNavigationMetadata, ChecksRequestBuilderRequestsMetadata } from './checks/index.js';
/**
 * Uri template for the request builder.
 */
export const UptimeRequestBuilderUriTemplate = "{+baseurl}/v2/uptime";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UptimeRequestBuilderNavigationMetadata = {
    checks: {
        requestsMetadata: ChecksRequestBuilderRequestsMetadata,
        navigationMetadata: ChecksRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
