/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createMetricsFromDiscriminatorValue } from '../../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const Frontend_http_responsesRequestBuilderUriTemplate = "{+baseurl}/v2/monitoring/metrics/load_balancer/frontend_http_responses?end={end}&lb_id={lb_id}&start={start}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const Frontend_http_responsesRequestBuilderGetQueryParametersMapper = {
    "lbId": "lb_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Frontend_http_responsesRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: Frontend_http_responsesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createMetricsFromDiscriminatorValue,
        queryParametersMapper: Frontend_http_responsesRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
