/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue, createKernelFromDiscriminatorValue, createMeta_propertiesFromDiscriminatorValue, createPage_linksFromDiscriminatorValue, serializeKernel, serializeMeta_properties, serializePage_links } from '../../../../models/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {KernelsGetResponse}
 */
// @ts-ignore
export function createKernelsGetResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoKernelsGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoKernelsGetResponse(kernelsGetResponse = {}) {
    return {
        "kernels": n => { kernelsGetResponse.kernels = n.getCollectionOfObjectValues(createKernelFromDiscriminatorValue); },
        "links": n => { kernelsGetResponse.links = n.getObjectValue(createPage_linksFromDiscriminatorValue); },
        "meta": n => { kernelsGetResponse.meta = n.getObjectValue(createMeta_propertiesFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeKernelsGetResponse(writer, kernelsGetResponse = {}) {
    if (kernelsGetResponse) {
        writer.writeCollectionOfObjectValues("kernels", kernelsGetResponse.kernels, serializeKernel);
        writer.writeObjectValue("links", kernelsGetResponse.links, serializePage_links);
        writer.writeObjectValue("meta", kernelsGetResponse.meta, serializeMeta_properties);
        writer.writeAdditionalData(kernelsGetResponse.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const KernelsRequestBuilderUriTemplate = "{+baseurl}/v2/droplets/{droplet_id}/kernels{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const KernelsRequestBuilderGetQueryParametersMapper = {
    "perPage": "per_page",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const KernelsRequestBuilderRequestsMetadata = {
    get: {
        uriTemplate: KernelsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createKernelsGetResponseFromDiscriminatorValue,
        queryParametersMapper: KernelsRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
