/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue } from '../../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const WithToken_ItemRequestBuilderUriTemplate = "{+baseurl}/v2/dedicated-inferences/{dedicated_inference_id}/tokens/{token_id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithToken_ItemRequestBuilderRequestsMetadata = {
    delete: {
        uriTemplate: WithToken_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
