/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreate_secret_responseFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, createSecret_list_itemFromDiscriminatorValue, serializeCreate_secret_response, serializeSecret_list_item, type Create_secret_response, type ErrorEscaped, type Secret_list_item } from '../../../models/index.js';
// @ts-ignore
import { type WithSecretItemRequestBuilder, WithSecretItemRequestBuilderNavigationMetadata, WithSecretItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SecretsGetResponse_links_pages}
 */
// @ts-ignore
export function createSecretsGetResponse_links_pagesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSecretsGetResponse_links_pages;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SecretsGetResponse_links}
 */
// @ts-ignore
export function createSecretsGetResponse_linksFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSecretsGetResponse_links;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SecretsGetResponse_meta}
 */
// @ts-ignore
export function createSecretsGetResponse_metaFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSecretsGetResponse_meta;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SecretsGetResponse}
 */
// @ts-ignore
export function createSecretsGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSecretsGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SecretsPostRequestBody_values}
 */
// @ts-ignore
export function createSecretsPostRequestBody_valuesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSecretsPostRequestBody_values;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SecretsPostRequestBody}
 */
// @ts-ignore
export function createSecretsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSecretsPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param SecretsGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSecretsGetResponse(secretsGetResponse: Partial<SecretsGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "links": n => { secretsGetResponse.links = n.getObjectValue<SecretsGetResponse_links>(createSecretsGetResponse_linksFromDiscriminatorValue); },
        "meta": n => { secretsGetResponse.meta = n.getObjectValue<SecretsGetResponse_meta>(createSecretsGetResponse_metaFromDiscriminatorValue); },
        "secrets": n => { secretsGetResponse.secrets = n.getCollectionOfObjectValues<Secret_list_item>(createSecret_list_itemFromDiscriminatorValue); },
        "unavailable_regions": n => { secretsGetResponse.unavailableRegions = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SecretsGetResponse_links The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSecretsGetResponse_links(secretsGetResponse_links: Partial<SecretsGetResponse_links> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "pages": n => { secretsGetResponse_links.pages = n.getObjectValue<SecretsGetResponse_links_pages>(createSecretsGetResponse_links_pagesFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SecretsGetResponse_links_pages The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSecretsGetResponse_links_pages(secretsGetResponse_links_pages: Partial<SecretsGetResponse_links_pages> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "first": n => { secretsGetResponse_links_pages.first = n.getStringValue(); },
        "last": n => { secretsGetResponse_links_pages.last = n.getStringValue(); },
        "next": n => { secretsGetResponse_links_pages.next = n.getStringValue(); },
        "prev": n => { secretsGetResponse_links_pages.prev = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SecretsGetResponse_meta The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSecretsGetResponse_meta(secretsGetResponse_meta: Partial<SecretsGetResponse_meta> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "page": n => { secretsGetResponse_meta.page = n.getNumberValue(); },
        "pages": n => { secretsGetResponse_meta.pages = n.getNumberValue(); },
        "total": n => { secretsGetResponse_meta.total = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SecretsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSecretsPostRequestBody(secretsPostRequestBody: Partial<SecretsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { secretsPostRequestBody.name = n.getStringValue(); },
        "region": n => { secretsPostRequestBody.region = n.getStringValue(); },
        "values": n => { secretsPostRequestBody.values = n.getObjectValue<SecretsPostRequestBody_values>(createSecretsPostRequestBody_valuesFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param SecretsPostRequestBody_values The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSecretsPostRequestBody_values(secretsPostRequestBody_values: Partial<SecretsPostRequestBody_values> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface SecretsGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The links property
     */
    links?: SecretsGetResponse_links | null;
    /**
     * The meta property
     */
    meta?: SecretsGetResponse_meta | null;
    /**
     * The secrets property
     */
    secrets?: Secret_list_item[] | null;
    /**
     * Regions that could not be queried while building the list response.
     */
    unavailableRegions?: string[] | null;
}
export interface SecretsGetResponse_links extends AdditionalDataHolder, Parsable {
    /**
     * The pages property
     */
    pages?: SecretsGetResponse_links_pages | null;
}
export interface SecretsGetResponse_links_pages extends AdditionalDataHolder, Parsable {
    /**
     * URL for the first page of results.
     */
    first?: string | null;
    /**
     * URL for the last page of results.
     */
    last?: string | null;
    /**
     * URL for the next page of results.
     */
    next?: string | null;
    /**
     * URL for the previous page of results.
     */
    prev?: string | null;
}
export interface SecretsGetResponse_meta extends AdditionalDataHolder, Parsable {
    /**
     * The current page number.
     */
    page?: number | null;
    /**
     * The total number of pages.
     */
    pages?: number | null;
    /**
     * The total number of secrets across all regions.
     */
    total?: number | null;
}
export interface SecretsPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The name of the secret to create.
     */
    name?: string | null;
    /**
     * The region where the secret will be stored.
     */
    region?: string | null;
    /**
     * Key-value pairs to store in the secret.
     */
    values?: SecretsPostRequestBody_values | null;
}
/**
 * Key-value pairs to store in the secret.
 */
export interface SecretsPostRequestBody_values extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /v2/security/secrets
 */
export interface SecretsRequestBuilder extends BaseRequestBuilder<SecretsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v2.security.secrets.item collection
     * @param secret The name of the secret.
     * @returns {WithSecretItemRequestBuilder}
     */
     bySecret(secret: string) : WithSecretItemRequestBuilder;
    /**
     * To list secrets across all configured regions, send a GET request to `/v2/security/secrets`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SecretsGetResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<SecretsRequestBuilderGetQueryParameters> | undefined) : Promise<SecretsGetResponse | undefined>;
    /**
     * To create a secret, send a POST request to `/v2/security/secrets`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Create_secret_response>}
     * @throws {ErrorEscaped} error when the service returns a 400 status code
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     post(body: SecretsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Create_secret_response | undefined>;
    /**
     * To list secrets across all configured regions, send a GET request to `/v2/security/secrets`.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SecretsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * To create a secret, send a POST request to `/v2/security/secrets`.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SecretsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * To list secrets across all configured regions, send a GET request to `/v2/security/secrets`.
 */
export interface SecretsRequestBuilderGetQueryParameters {
    /**
     * Which 'page' of paginated results to return.
     */
    page?: number;
    /**
     * Number of items returned per page
     */
    perPage?: number;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SecretsGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSecretsGetResponse(writer: SerializationWriter, secretsGetResponse: Partial<SecretsGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!secretsGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SecretsGetResponse_links>("links", secretsGetResponse.links, serializeSecretsGetResponse_links);
    writer.writeObjectValue<SecretsGetResponse_meta>("meta", secretsGetResponse.meta, serializeSecretsGetResponse_meta);
    writer.writeCollectionOfObjectValues<Secret_list_item>("secrets", secretsGetResponse.secrets, serializeSecret_list_item);
    writer.writeCollectionOfPrimitiveValues<string>("unavailable_regions", secretsGetResponse.unavailableRegions);
    writer.writeAdditionalData(secretsGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SecretsGetResponse_links The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSecretsGetResponse_links(writer: SerializationWriter, secretsGetResponse_links: Partial<SecretsGetResponse_links> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!secretsGetResponse_links || isSerializingDerivedType) { return; }
    writer.writeObjectValue<SecretsGetResponse_links_pages>("pages", secretsGetResponse_links.pages, serializeSecretsGetResponse_links_pages);
    writer.writeAdditionalData(secretsGetResponse_links.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SecretsGetResponse_links_pages The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSecretsGetResponse_links_pages(writer: SerializationWriter, secretsGetResponse_links_pages: Partial<SecretsGetResponse_links_pages> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!secretsGetResponse_links_pages || isSerializingDerivedType) { return; }
    writer.writeStringValue("first", secretsGetResponse_links_pages.first);
    writer.writeStringValue("last", secretsGetResponse_links_pages.last);
    writer.writeStringValue("next", secretsGetResponse_links_pages.next);
    writer.writeStringValue("prev", secretsGetResponse_links_pages.prev);
    writer.writeAdditionalData(secretsGetResponse_links_pages.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SecretsGetResponse_meta The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSecretsGetResponse_meta(writer: SerializationWriter, secretsGetResponse_meta: Partial<SecretsGetResponse_meta> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!secretsGetResponse_meta || isSerializingDerivedType) { return; }
    writer.writeNumberValue("page", secretsGetResponse_meta.page);
    writer.writeNumberValue("pages", secretsGetResponse_meta.pages);
    writer.writeNumberValue("total", secretsGetResponse_meta.total);
    writer.writeAdditionalData(secretsGetResponse_meta.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SecretsPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSecretsPostRequestBody(writer: SerializationWriter, secretsPostRequestBody: Partial<SecretsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!secretsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", secretsPostRequestBody.name);
    writer.writeStringValue("region", secretsPostRequestBody.region);
    writer.writeObjectValue<SecretsPostRequestBody_values>("values", secretsPostRequestBody.values, serializeSecretsPostRequestBody_values);
    writer.writeAdditionalData(secretsPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SecretsPostRequestBody_values The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSecretsPostRequestBody_values(writer: SerializationWriter, secretsPostRequestBody_values: Partial<SecretsPostRequestBody_values> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!secretsPostRequestBody_values || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(secretsPostRequestBody_values.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const SecretsRequestBuilderUriTemplate = "{+baseurl}/v2/security/secrets{?page*,per_page*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SecretsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SecretsRequestBuilderNavigationMetadata: Record<Exclude<keyof SecretsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySecret: {
        requestsMetadata: WithSecretItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithSecretItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["secret"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SecretsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SecretsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSecretsGetResponseFromDiscriminatorValue,
        queryParametersMapper: SecretsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: SecretsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createCreate_secret_responseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSecretsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
