/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MysqlRequestBuilderNavigationMetadata, type MysqlRequestBuilder } from './mysql/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/monitoring/metrics/database
 */
export interface DatabaseRequestBuilder extends BaseRequestBuilder<DatabaseRequestBuilder> {
    /**
     * The mysql property
     */
    get mysql(): MysqlRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const DatabaseRequestBuilderUriTemplate = "{+baseurl}/v2/monitoring/metrics/database";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DatabaseRequestBuilderNavigationMetadata: Record<Exclude<keyof DatabaseRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    mysql: {
        navigationMetadata: MysqlRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
