/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorEscapedFromDiscriminatorValue } from '../../../../models/index.js';
/**
 * Uri template for the request builder.
 */
export const Install_updateRequestBuilderUriTemplate = "{+baseurl}/v2/databases/{database_cluster_uuid}/install_update";
/**
 * Metadata for all the requests in the request builder.
 */
export const Install_updateRequestBuilderRequestsMetadata = {
    put: {
        uriTemplate: Install_updateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
