/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithShare_ItemRequestBuilder, WithShare_ItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v2/nfs/shares
 */
export interface SharesRequestBuilder extends BaseRequestBuilder<SharesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v2.nfs.shares.item collection
     * @param share_id The unique identifier of the NFS share.
     * @returns {WithShare_ItemRequestBuilder}
     */
     byShare_id(share_id: Guid) : WithShare_ItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SharesRequestBuilderUriTemplate = "{+baseurl}/v2/nfs/shares";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SharesRequestBuilderNavigationMetadata: Record<Exclude<keyof SharesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byShare_id: {
        navigationMetadata: WithShare_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["share_id"],
    },
};
/* tslint:enable */
/* eslint-enable */
