/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createApp_rollback_validation_conditionFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeApp_rollback_validation_condition, serializeApps_rollback_app_request } from '../../../../../models/index.js';
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ValidatePostResponse}
 */
// @ts-ignore
export function createValidatePostResponseFromDiscriminatorValue(parseNode) {
    return deserializeIntoValidatePostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoValidatePostResponse(validatePostResponse = {}) {
    return {
        "error": n => { validatePostResponse.errorEscaped = n.getObjectValue(createApp_rollback_validation_conditionFromDiscriminatorValue); },
        "valid": n => { validatePostResponse.valid = n.getBooleanValue(); },
        "warnings": n => { validatePostResponse.warnings = n.getCollectionOfObjectValues(createApp_rollback_validation_conditionFromDiscriminatorValue); },
    };
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeValidatePostResponse(writer, validatePostResponse = {}) {
    if (validatePostResponse) {
        writer.writeObjectValue("error", validatePostResponse.errorEscaped, serializeApp_rollback_validation_condition);
        writer.writeBooleanValue("valid", validatePostResponse.valid);
        writer.writeCollectionOfObjectValues("warnings", validatePostResponse.warnings, serializeApp_rollback_validation_condition);
    }
}
/**
 * Uri template for the request builder.
 */
export const ValidateRequestBuilderUriTemplate = "{+baseurl}/v2/apps/{app_%2Did}/rollback/validate";
/**
 * Metadata for all the requests in the request builder.
 */
export const ValidateRequestBuilderRequestsMetadata = {
    post: {
        uriTemplate: ValidateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue,
            404: createErrorEscapedFromDiscriminatorValue,
            429: createErrorEscapedFromDiscriminatorValue,
            500: createErrorEscapedFromDiscriminatorValue,
            XXX: createErrorEscapedFromDiscriminatorValue,
        },
        adapterMethodName: "send",
        responseBodyFactory: createValidatePostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeApps_rollback_app_request,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
