/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDedicated_inference_access_tokenFromDiscriminatorValue, createDedicated_inferenceFromDiscriminatorValue, createErrorEscapedFromDiscriminatorValue, serializeDedicated_inference, serializeDedicated_inference_access_token, serializeDedicated_inference_create_request, type Dedicated_inference, type Dedicated_inference_access_token, type Dedicated_inference_create_request, type ErrorEscaped } from '../../models/index.js';
// @ts-ignore
import { GpuModelConfigRequestBuilderRequestsMetadata, type GpuModelConfigRequestBuilder } from './gpuModelConfig/index.js';
// @ts-ignore
import { type WithDedicated_inference_ItemRequestBuilder, WithDedicated_inference_ItemRequestBuilderNavigationMetadata, WithDedicated_inference_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { SizesRequestBuilderRequestsMetadata, type SizesRequestBuilder } from './sizes/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DedicatedInferencesGetResponse_links_pages}
 */
// @ts-ignore
export function createDedicatedInferencesGetResponse_links_pagesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDedicatedInferencesGetResponse_links_pages;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DedicatedInferencesGetResponse_links}
 */
// @ts-ignore
export function createDedicatedInferencesGetResponse_linksFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDedicatedInferencesGetResponse_links;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DedicatedInferencesGetResponse_meta}
 */
// @ts-ignore
export function createDedicatedInferencesGetResponse_metaFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDedicatedInferencesGetResponse_meta;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DedicatedInferencesGetResponse}
 */
// @ts-ignore
export function createDedicatedInferencesGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDedicatedInferencesGetResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {DedicatedInferencesPostResponse}
 */
// @ts-ignore
export function createDedicatedInferencesPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoDedicatedInferencesPostResponse;
}
export interface DedicatedInferencesGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * Array of Dedicated Inference instances.
     */
    dedicatedInferences?: Dedicated_inference[] | null;
    /**
     * The links property
     */
    links?: DedicatedInferencesGetResponse_links | null;
    /**
     * The meta property
     */
    meta?: DedicatedInferencesGetResponse_meta | null;
}
export interface DedicatedInferencesGetResponse_links extends AdditionalDataHolder, Parsable {
    /**
     * Pagination links (first, prev, next, last).
     */
    pages?: DedicatedInferencesGetResponse_links_pages | null;
}
/**
 * Pagination links (first, prev, next, last).
 */
export interface DedicatedInferencesGetResponse_links_pages extends AdditionalDataHolder, Parsable {
}
export interface DedicatedInferencesGetResponse_meta extends AdditionalDataHolder, Parsable {
    /**
     * Total number of results.
     */
    total?: number | null;
}
export interface DedicatedInferencesPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * A Dedicated Inference instance.
     */
    dedicatedInference?: Dedicated_inference | null;
    /**
     * Access token for authenticating to Dedicated Inference endpoints.
     */
    token?: Dedicated_inference_access_token | null;
}
/**
 * Builds and executes requests for operations under /v2/dedicated-inferences
 */
export interface DedicatedInferencesRequestBuilder extends BaseRequestBuilder<DedicatedInferencesRequestBuilder> {
    /**
     * The gpuModelConfig property
     */
    get gpuModelConfig(): GpuModelConfigRequestBuilder;
    /**
     * The sizes property
     */
    get sizes(): SizesRequestBuilder;
    /**
     * Gets an item from the ApiSdk.v2.dedicatedInferences.item collection
     * @param dedicated_inference_id A unique identifier for a Dedicated Inference instance.
     * @returns {WithDedicated_inference_ItemRequestBuilder}
     */
     byDedicated_inference_id(dedicated_inference_id: Guid) : WithDedicated_inference_ItemRequestBuilder;
    /**
     * List all Dedicated Inference instances for your team. Send a GET request to`/v2/dedicated-inferences`. You may filter by region and use page and per_pagefor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DedicatedInferencesGetResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     get(requestConfiguration?: RequestConfiguration<DedicatedInferencesRequestBuilderGetQueryParameters> | undefined) : Promise<DedicatedInferencesGetResponse | undefined>;
    /**
     * Create a new Dedicated Inference for your team. Send a POST request to`/v2/dedicated-inferences` with a `spec` object (version, name, region, vpc,enable_public_endpoint, model_deployments) and optional `access_tokens` (e.g.hugging_face_token for gated models). The response code 202 Accepted indicatesthe request was accepted for processing; it does not indicate success or failure.The token value is returned only on create; store it securely.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DedicatedInferencesPostResponse>}
     * @throws {ErrorEscaped} error when the service returns a 401 status code
     * @throws {ErrorEscaped} error when the service returns a 429 status code
     * @throws {ErrorEscaped} error when the service returns a 500 status code
     * @throws {ErrorEscaped} error when the service returns a 4XX or 5XX status code
     */
     post(body: Dedicated_inference_create_request, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DedicatedInferencesPostResponse | undefined>;
    /**
     * List all Dedicated Inference instances for your team. Send a GET request to`/v2/dedicated-inferences`. You may filter by region and use page and per_pagefor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DedicatedInferencesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a new Dedicated Inference for your team. Send a POST request to`/v2/dedicated-inferences` with a `spec` object (version, name, region, vpc,enable_public_endpoint, model_deployments) and optional `access_tokens` (e.g.hugging_face_token for gated models). The response code 202 Accepted indicatesthe request was accepted for processing; it does not indicate success or failure.The token value is returned only on create; store it securely.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: Dedicated_inference_create_request, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * List all Dedicated Inference instances for your team. Send a GET request to`/v2/dedicated-inferences`. You may filter by region and use page and per_pagefor pagination.
 */
export interface DedicatedInferencesRequestBuilderGetQueryParameters {
    /**
     * Which 'page' of paginated results to return.
     */
    page?: number;
    /**
     * Number of items returned per page
     */
    perPage?: number;
    /**
     * Filter by region. Dedicated Inference is only available in nyc2, tor1, and atl1.
     */
    region?: GetRegionQueryParameterType;
}
/**
 * The deserialization information for the current model
 * @param DedicatedInferencesGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDedicatedInferencesGetResponse(dedicatedInferencesGetResponse: Partial<DedicatedInferencesGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "dedicated_inferences": n => { dedicatedInferencesGetResponse.dedicatedInferences = n.getCollectionOfObjectValues<Dedicated_inference>(createDedicated_inferenceFromDiscriminatorValue); },
        "links": n => { dedicatedInferencesGetResponse.links = n.getObjectValue<DedicatedInferencesGetResponse_links>(createDedicatedInferencesGetResponse_linksFromDiscriminatorValue); },
        "meta": n => { dedicatedInferencesGetResponse.meta = n.getObjectValue<DedicatedInferencesGetResponse_meta>(createDedicatedInferencesGetResponse_metaFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param DedicatedInferencesGetResponse_links The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDedicatedInferencesGetResponse_links(dedicatedInferencesGetResponse_links: Partial<DedicatedInferencesGetResponse_links> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "pages": n => { dedicatedInferencesGetResponse_links.pages = n.getObjectValue<DedicatedInferencesGetResponse_links_pages>(createDedicatedInferencesGetResponse_links_pagesFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param DedicatedInferencesGetResponse_links_pages The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDedicatedInferencesGetResponse_links_pages(dedicatedInferencesGetResponse_links_pages: Partial<DedicatedInferencesGetResponse_links_pages> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param DedicatedInferencesGetResponse_meta The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDedicatedInferencesGetResponse_meta(dedicatedInferencesGetResponse_meta: Partial<DedicatedInferencesGetResponse_meta> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "total": n => { dedicatedInferencesGetResponse_meta.total = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param DedicatedInferencesPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoDedicatedInferencesPostResponse(dedicatedInferencesPostResponse: Partial<DedicatedInferencesPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "dedicated_inference": n => { dedicatedInferencesPostResponse.dedicatedInference = n.getObjectValue<Dedicated_inference>(createDedicated_inferenceFromDiscriminatorValue); },
        "token": n => { dedicatedInferencesPostResponse.token = n.getObjectValue<Dedicated_inference_access_token>(createDedicated_inference_access_tokenFromDiscriminatorValue); },
    }
}
export type GetRegionQueryParameterType = (typeof GetRegionQueryParameterTypeObject)[keyof typeof GetRegionQueryParameterTypeObject];
/**
 * Serializes information the current object
 * @param DedicatedInferencesGetResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDedicatedInferencesGetResponse(writer: SerializationWriter, dedicatedInferencesGetResponse: Partial<DedicatedInferencesGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dedicatedInferencesGetResponse || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<Dedicated_inference>("dedicated_inferences", dedicatedInferencesGetResponse.dedicatedInferences, serializeDedicated_inference);
    writer.writeObjectValue<DedicatedInferencesGetResponse_links>("links", dedicatedInferencesGetResponse.links, serializeDedicatedInferencesGetResponse_links);
    writer.writeObjectValue<DedicatedInferencesGetResponse_meta>("meta", dedicatedInferencesGetResponse.meta, serializeDedicatedInferencesGetResponse_meta);
    writer.writeAdditionalData(dedicatedInferencesGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param DedicatedInferencesGetResponse_links The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDedicatedInferencesGetResponse_links(writer: SerializationWriter, dedicatedInferencesGetResponse_links: Partial<DedicatedInferencesGetResponse_links> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dedicatedInferencesGetResponse_links || isSerializingDerivedType) { return; }
    writer.writeObjectValue<DedicatedInferencesGetResponse_links_pages>("pages", dedicatedInferencesGetResponse_links.pages, serializeDedicatedInferencesGetResponse_links_pages);
    writer.writeAdditionalData(dedicatedInferencesGetResponse_links.additionalData);
}
/**
 * Serializes information the current object
 * @param DedicatedInferencesGetResponse_links_pages The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDedicatedInferencesGetResponse_links_pages(writer: SerializationWriter, dedicatedInferencesGetResponse_links_pages: Partial<DedicatedInferencesGetResponse_links_pages> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dedicatedInferencesGetResponse_links_pages || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(dedicatedInferencesGetResponse_links_pages.additionalData);
}
/**
 * Serializes information the current object
 * @param DedicatedInferencesGetResponse_meta The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDedicatedInferencesGetResponse_meta(writer: SerializationWriter, dedicatedInferencesGetResponse_meta: Partial<DedicatedInferencesGetResponse_meta> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dedicatedInferencesGetResponse_meta || isSerializingDerivedType) { return; }
    writer.writeNumberValue("total", dedicatedInferencesGetResponse_meta.total);
    writer.writeAdditionalData(dedicatedInferencesGetResponse_meta.additionalData);
}
/**
 * Serializes information the current object
 * @param DedicatedInferencesPostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeDedicatedInferencesPostResponse(writer: SerializationWriter, dedicatedInferencesPostResponse: Partial<DedicatedInferencesPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!dedicatedInferencesPostResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<Dedicated_inference>("dedicated_inference", dedicatedInferencesPostResponse.dedicatedInference, serializeDedicated_inference);
    writer.writeObjectValue<Dedicated_inference_access_token>("token", dedicatedInferencesPostResponse.token, serializeDedicated_inference_access_token);
    writer.writeAdditionalData(dedicatedInferencesPostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const DedicatedInferencesRequestBuilderUriTemplate = "{+baseurl}/v2/dedicated-inferences{?page*,per_page*,region*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const DedicatedInferencesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "perPage": "per_page",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DedicatedInferencesRequestBuilderNavigationMetadata: Record<Exclude<keyof DedicatedInferencesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byDedicated_inference_id: {
        requestsMetadata: WithDedicated_inference_ItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithDedicated_inference_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["dedicated_inference_id"],
    },
    gpuModelConfig: {
        requestsMetadata: GpuModelConfigRequestBuilderRequestsMetadata,
    },
    sizes: {
        requestsMetadata: SizesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DedicatedInferencesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DedicatedInferencesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDedicatedInferencesGetResponseFromDiscriminatorValue,
        queryParametersMapper: DedicatedInferencesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: DedicatedInferencesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            401: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            429: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
            XXX: createErrorEscapedFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createDedicatedInferencesPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDedicated_inference_create_request,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
export const GetRegionQueryParameterTypeObject = {
    Nyc2: "nyc2",
    Tor1: "tor1",
    Atl1: "atl1",
} as const;
/* tslint:enable */
/* eslint-enable */
